In [1]:
import numpy as np

In [2]:
#Question-1
np.arange(2,50,3)

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

In [8]:
#Question-2
arr_1 = np.array([int(x) for x in input().split()])
arr_2 = np.array([int(x) for x in input().split()])
arr_3=np.concatenate((arr_1,arr_2),axis=0)
print(arr_3)
print(np.sort(arr_3))

1 7 3
4 8 2
[1 7 3 4 8 2]
[1 2 3 4 7 8]


In [14]:
#Question-3
arr = np.array( [ [ [1,4,6,8],[3,4,9,6],[2,9,6,4] ]])
print("Dimensions of the array : ",arr.ndim)
print("Size of array : ",arr.size)

Dimensions of the array :  3
Size of array :  12


In [25]:
#Question-4

arr = np.array( [3,5,1,7,8,10] )
print("Before converting ",arr)

print(np.expand_dims(arr,1))

#After converting into 2-d array
arr.resize((2,3))
print("After converting into 2d array",arr)

Before converting  [ 3  5  1  7  8 10]
[[ 3]
 [ 5]
 [ 1]
 [ 7]
 [ 8]
 [10]]
After converting into 2d array [[ 3  5  1]
 [ 7  8 10]]


In [31]:
#Question-5
arr1 = np.array( [ [ 1,2,3,4,5],[6,7,8,9,10] ] )
arr2 = np.array( [ [ 11,12,13,14,15],[16,17,18,19,20] ] )
print(arr1)
print(arr2)
print("\n")
print("Stcaked Vertically",np.vstack((arr1,arr2)))
print("\n")
print("Stacked Horizantally",np.hstack((arr1,arr2)))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[11 12 13 14 15]
 [16 17 18 19 20]]


Stcaked Vertically [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


Stacked Horizantally [[ 1  2  3  4  5 11 12 13 14 15]
 [ 6  7  8  9 10 16 17 18 19 20]]


In [35]:
#Question-5
list = np.array([1, 1, 2, 3, 4, 4, 1])

(unique_numbers, counts) = np.unique(list, return_counts=True)


print(unique_numbers)
print(counts)

[1 2 3 4]
[3 1 1 2]
